# Generated by Django 5.0.6 on 2024-06-22 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('angle', models.IntegerField()),
                ('distance', models.FloatField()),
            ],
            options={
                'verbose_name': 'Car Mapping',
                'verbose_name_plural': 'Car Mappings',
            },
        ),
    ]
