# Generated by Django 5.1a1 on 2024-07-01 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapCreation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EndpointUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.CharField(max_length=100)),
                ('start_time', models.DateTimeField()),
            ],
        ),
    ]
