# Generated by Django 5.0.6 on 2024-07-11 05:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapCreation', '0003_car'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='car_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Obstacle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('angle', models.IntegerField()),
                ('distance', models.FloatField()),
                ('x_position', models.DecimalField(decimal_places=2, max_digits=10)),
                ('y_position', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Obstacle',
                'verbose_name_plural': 'Obstacles',
            },
        ),
        migrations.DeleteModel(
            name='CarMapping',
        ),
        migrations.AddField(
            model_name='car',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='car_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mapCreation.carimage'),
        ),
        migrations.AddField(
            model_name='car',
            name='surroundings',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mapCreation.obstacle'),
        ),
    ]
