# Generated by Django 5.0.6 on 2024-07-11 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapCreation', '0004_carimage_obstacle_delete_carmapping_car_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_angle',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_x',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_y',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='obstacle',
            name='angle',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='obstacle',
            name='x_position',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='obstacle',
            name='y_position',
            field=models.FloatField(),
        ),
    ]
